Repository FilGoodInc/oxygencs-grp1-eq6, pull requests merged in 2024-07, with the labels that each got.

#1 Re-add templates
  .github/ISSUE_TEMPLATE/ajout-de-fonctionnalité.md
  .github/ISSUE_TEMPLATE/rapport-de-bug.md
  pull_request_template.md
Labels: documentation

#4 Docker oxygen
  .env
  Dockerfile
  README.md
Labels: documentation, fonctionnalité

#5 Pre commit hook
  .env
  .gitignore
  .pre-commit-config.yaml
  .pylintrc
  Dockerfile
  Pipfile
  Pipfile.lock
  README.md
  pull_request_template.md
  pytest.ini
  src/main.py
  test/test.py
  test/test_unit.py
Labels: documentation, fonctionnalité

#6 pytest for pre commit et ci
  .github/workflows/docker-image.yml
  .pre-commit-config.yaml
  Pipfile
  Pipfile.lock
  src/main.py
  test/test_integration.py
Labels: fonctionnalité

#7 Deployement docker
  .github/workflows/docker-image.yml
Labels: bug

#10 kubernetes config
  .gitignore
  k8s/configmap.yaml
  k8s/secret.yaml
Labels: fonctionnalité

#11 deployment sur kubernetes
  k8s/deployment-hvac.yaml
Labels: fonctionnalité
